version: '3.6'

services:
  web:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    ports:
     - "9000:9000"
    environment:
     HTTP_PORT: 9000
     CONNECTION_LOCALZK_NAME: zoo1
     CONNECTION_LOCALZK_CONN: localhost:2181
    restart: always

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

