# Generated by Django 4.0.4 on 2022-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_host_hostavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='title',
            field=models.CharField(default='title', max_length=500),
        ),
    ]
