# Generated by Django 4.0.4 on 2022-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_host_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
