# Generated by Django 4.0.4 on 2022-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_host_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
