# Generated by Django 4.0.4 on 2022-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_host_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
