---
- name: Add apt repository
  apt_repository:
    #repo: deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ 'ubuntu-arm64 focal main' if ansible_architecture == 'aarch64' else 'debian buster main' }}
    repo: deb https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
    state: present
    update_cache: yes


- name: Remove old agent
  apt:
    pkg:
      - zabbix-agent
    state: absent
    purge: yes
    force: yes
  ignore_errors: true
