---
- name: Install iptables
  apt:
    name:
      - ipset
      - ferm
    cache_valid_time: 600
  tags:
    - iptables

- name: Remove iptables-persistent
  apt:
    name: iptables-persistent
    state: absent
    purge: yes
    force: yes
  tags:
    - iptables

- name: Copy ipset_reload
  copy:
    src: ipset-reload.sh
    dest: /usr/local/bin/ipset-reload.sh
    mode: u=rxw,g=r,o=r
    owner: root
    group: root
  tags:
    - iptables

- name: Create ipset tables
  template:
    src: ipset.tables.j2
    dest: /etc/ipset.tables
  notify:
    - Reload ipset tables
    - Fill up ipsets
    - Reload ferm
  tags:
    - ipset
    - iptables

- name: Copy /etc/default/ferm
  copy:
    src: default-ferm
    dest: /etc/default/ferm
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Reload ferm
  tags:
    - ferm
    - iptables

- name: Generate /etc/ferm/ferm.conf
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    mode: u=rw,g=r,o=r
    owner: root
    group: root
  notify: Reload ferm
  tags:
    - ferm
    - iptables


- name: Update ferm service file
  template:
    src: ferm-systemd-unit.j2
    dest: /lib/systemd/system/ferm.service
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: result_update_file
  notify: Systemctl daemon-reload
  tags:
    - ferm
    - iptables

- name: Run systemctl daemon-reload # noqa 503
  systemd:
    daemon_reload: yes
  when: result_update_file.changed
  tags:
    - ferm
    - iptables

