---
- name: Add the user 'admin' with a bash shell, and groups docker, sudo
  ansible.builtin.user:
    name: admin
    shell: /bin/bash
    create_home: true
    home: /home/admin
    groups: sudo,docker
    append: yes


- name: Allow the user admin to do sudo commands without password
  community.general.sudoers:
    name: allow-admin-sudo
    state: present
    user: admin
    commands: ALL

- name: Set authorized key taken from file
  authorized_key:
    user: admin
    state: present
    key: "{{ lookup('file', './key_for_test.pub') }}"