global:
  scrape_interval: 15s

rule_files:
  - '/prometheus/alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: telegraf
    scrape_interval: 5s
    static_configs:
      - targets:
        - telegraf:8125

  - job_name: node-exporter-autodiscovery
    http_sd_configs:
    - url: http://176.57.212.153:8888

  - job_name: cadvisor-autodiscovery
    http_sd_configs:
    - url: http://176.57.212.153:8888/cadvisor
