#- name: Install docker & create folder for logs
---
  - gather_facts: true
    hosts: vmware-srv
    become: yes
#    become_user: root
#    become_method: su
    roles:
#      - create_admin_user
      - docker
#      - atop
#      - node-exporter
#      - zk-register
#       - cadvisor-service
