#- name: Install docker & create folder for logs
---
  - gather_facts: true
    hosts: srv-work
    become: yes
    roles:
#      - create_admin_user
#      - docker
#      - atop
#      - node-exporter
#      - zk-register
       - cadvisor-service
