
- name: Step1
  gather_facts: true
  hosts: all
  remote_user: igor
  become: yes
  #become_method: sudo

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Show Uptime
      ansible.builtin.shell: uptime
      register: result

#    - name: Show result 
#      ansible.builtin.debug:
#        var: result

    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: yes