---    
- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update-cache: true
    cache_valid_time: 86400

- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update-cache: true

- name: Check docker installed
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Get docker-compose last version
  uri:
    url: "https://api.github.com/repos/docker/compose/releases/latest"
    body_format: json
  register: page

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755  

- name: Finish install
  block:
    - name: Add user to docker group
      user:
        name: "{{ansible_user}}"
        append: yes
        groups: docker

#    - name: Server restart
#      reboot: