global:
  scrape_interval: 15s

rule_files:
  - '/prometheus/alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: node-db
    static_configs:
      - targets: ['192.168.205.202:9100']

  - job_name: cadvisor-db
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.205.202:8080
